name: Build and deploy

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
  
      - name: Install node packages
        run: npm install --save-dev

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install --locked trunk

      - name: Build yew files
        run: trunk build

      # - name: Build tailwind packages
      #  run: npx tailwind -i $GITHUB_WORKSPACE/styles/tailwind.css -o $GITHUB_WORKSPACE/dist/app.css

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: $GITHUB_WORKSPACE/dist
          production-branch: main
          github-token: ${{ secrets.NETLIFY_GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOYMENT_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
